sudo: false

language: c

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.4
  - GHCVER=7.10.2
  - GHCVER=8.0.1

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.6.3
      - ghc-7.8.4
      - ghc-7.10.2
      - ghc-8.0.1
      - cabal-install-1.24

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:$PATH
  - (mkdir -p $HOME/.local/bin && cd $HOME/.local/bin && wget https://zalora-public.s3.amazonaws.com/tinc && chmod +x tinc)
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

install:
  - tinc

script:
  - cabal configure --enable-tests --ghc-options=-Werror --disable-optimization && cabal build && cabal test
  - cabal install --ghc-options=-Werror

cache:
  directories:
    - $HOME/.tinc/cache
