name: wai-make-assets
version: "0.1.1"
category: Development
maintainer: SoenkeHahn@gmail.com
synopsis: Compiling and serving assets
description: Small wai library and command line tool for compiling and serving assets (e.g. through ghcjs, elm, sass)
license: "BSD3"

github: soenkehahn/wai-make-assets

dependencies:
  - base < 99
  - wai-app-static
  - wai
  - warp
  - string-conversions
  - bytestring
  - data-default
  - filepath
  - shake
  - http-types
  - directory

ghc-options:
  -Wall -fno-warn-name-shadowing

library:
  source-dirs:
    - src

executables:
  wai-make-assets:
    main: wai-make-assets.hs
    source-dirs:
      - src
    dependencies:
      - getopt-generics

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - wreq
      - mockery
      - lens
      - silently
