name: elm-server

dependencies:
  - base
  - wai-app-static
  - wai
  - warp
  - string-conversions
  - bytestring
  - shake
  - http-types

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - hspec
      - wreq
      - mockery
      - lens
      - directory
