name: wai-make-assets
version: "0.1"

dependencies:
  - base
  - wai-app-static
  - wai
  - warp
  - string-conversions
  - bytestring
  - shake
  - http-types
  - directory

library:
  source-dirs:
    - src

executables:
  wai-make-assets:
    main: wai-make-assets.hs
    source-dirs:
      - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - wreq
      - mockery
      - lens
      - silently
